### ISSUE TITLE
Scala 3: Zinc does not fully propagate changes to inline methods

### ISSUE THREAD

**Issue by informarte** [sbt/zinc#1000] opened 2021-09-05 19:36 UTC
## versions

Scala 3.0.1, Mill 0.9.9, Zinc 1.5.5

## steps

Put the following objects into separate files:
```
object A {
  inline def f(x: Int) = x * 2
  def main(args: Array[String]): Unit = {
    println(f(10))
  }
}

object B {
  inline def g(x: Int) = A.f(x) * 2
  def main(args: Array[String]): Unit = {
    println(g(10))
  }
}

object C {
  inline def h(x: Int) = B.g(x) * 2
  def main(args: Array[String]): Unit = {
    println(h(10))
  }
}
```
Compile and run `C.main`; the output is `80`.

## problem

Now change the constant in `A.f` to 4 and recompile. Only 2 files get recompiled and the output of `C.main` is still 80.

## expectation

After changing `A.f`, all files get recompiled and the output of `C.main` is correct.

## notes

There seems to be now way to disable inlining in Scala 3. Hence it is very important that incremental compilation produces a correct result when an inlined method was changed. At the very least, a full rebuild should be triggered.

**Comment by smarter** [comment] 2021-09-05 19:45
Duplicate of https://github.com/lampepfl/dotty/issues/11861 (incremental compilation in scala 3 is implemented in the compiler repository, not in zinc's repository) Also note that there's an open pr for this issue: https://github.com/lampepfl/dotty/pull/12931

**Closed as completed by smarter** 2021-09-05 19:45 UTC

**Comment by informarte** [comment] 2021-09-06 06:01
Good to know, thanks.
