### ISSUE TITLE
Zinc locks a file after building with Maven, preventing the file from being deleted (Windows 10)

### ISSUE THREAD

**Issue by eyalroth** [sbt/zinc#404] opened 2017-09-04 13:06 UTC
Trying to clean a Maven project after a successful build integrated with Zinc often results in a failure; one of the distributed files cannot be deleted since it is locked by Zinc's process.

I'm pretty sure it's almost always the same file: A jar of one of the sub-modules in my multi-module Maven project, which is being used by the other modules (since it is a common/utility module).

It's probably important to note that I'm running on Windows 10. The funny thing is that both [process explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) and [IObit Unlocker](http://www.iobit.com/en/iobit-unlocker.php) do not detect that the file is being locked by another process.

**Comment by jvican** [comment] 2017-09-05 09:07
@eyalroth Thanks for reporting. Can you specify which file is locked by Zinc and provide a reproducible example? Otherwise, fixing this would be quite a challenging task. Also, you should bring this up with whomever created the Zinc integration for Maven. It's likely that a workaround can be found on the integration side.

**Comment by eyalroth** [comment] 2017-09-05 12:25
I was under the impression that the integration with Maven is being developed on this project as well.

Anyhow, I managed to reduce my original project to this very minimalistic example: 
[zinc-bug.zip](https://github.com/sbt/zinc/files/1277343/zinc-bug.zip)

Steps to reproduce:
1. Start Zinc server.
2. Run `mvn install` from the root of the example project.
3. Run `mvn clean` from the same location.

Make sure that when running `mvn install` you see the message `[INFO] Using zinc server for incremental compilation`.

**Comment by jvican** [comment] 2017-09-05 12:33
@eyalroth No, this repository is only for the incremental compiler. Integrations live elsewhere, e.g. sbt/sbt, pantsbuild/pants, etc.
  
After your last comment, it's become more obvious this is something you should bring up with the responsible of Maven's integration first. It's unclear if the integration is using the latest release 1.0, but the odds are against that since latest Zinc has undergone lots of changes, both in API and behaviour, and it's relatively recent (last month).
  
I would like to fix this if you get to reproduce it with Zinc 1.0, but so far it looks like this is not the best place to report this error.

**Comment by dwijnand** [comment] 2017-09-05 12:40
I would assume you're using https://github.com/davidB/scala-maven-plugin which uses the previous incarnation of "zinc": https://github.com/typesafehub/zinc.

With regards to scala-maven-plugin upgrading to Zinc 1 (this repo/issue tracker) their ticket is https://github.com/davidB/scala-maven-plugin/issues/208, which was closed; blocked on the request for a migration guide: https://github.com/sbt/zinc/issues/402.

**Comment by eyalroth** [comment] 2017-09-05 12:58
Thank you guys for your quick responses :)

@jvican Yeah, unfortunately, that seems to be the situation. I'm curious, is there any official release for a stand-alone app of Zinc 1.0?

@dwijnand Your assumptions are correct. I guess then it's rather pointless for me to use Zinc with Maven, as restarting the Zinc process over and over due to this bug removes the performance boost of the incremental build.

**Comment by jvican** [comment] 2017-09-05 13:01
> Yeah, unfortunately, that seems to be the situation. I'm curious, is there any official release for a stand-alone app of Zinc 1.0?
  
Sbt 1.0 uses Zinc 1.0 as of now. Pants has the integration ready and they want to ship it soon. Links to the integrations, if you're interested, can be found in #402.

**Comment by eyalroth** [comment] 2017-09-05 13:09
> Sbt 1.0 uses Zinc 1.0 as of now. Pants has the integration ready and they want to ship it soon. Links to the integrations, if you're interested, can be found in #402.

The old repo (https://github.com/typesafehub/zinc) had a stand-alone app release; is there a similar release on this repo for the newer versions of Zinc?

**Comment by jvican** [comment] 2017-09-05 13:12
@eyalroth No.

**Comment by dwijnand** [comment] 2017-09-05 13:14
There's no standalone nailgun server for Zinc 1, as there was for (typesafehub) Zinc 0.3.x. Anyone interested in upgrading scala-maven-plugin to Zinc 1 would need to resurrect that effort (or find another solution).

**Comment by jvican** [comment] 2017-09-05 13:17
Which links to https://github.com/sbt/zinc/issues/299.

**Comment by eyalroth** [comment] 2017-09-05 13:17
Alright, thank you very much guys. I guess you could close this issue (I've created a new one on the Maven plugin repo).

**Comment by jvican** [comment] 2017-09-05 13:18
Closing. If you decide to give any of those alternatives a try, I'll be happy to provide help in our Gitter channel.

**Closed as completed** 2017-09-05 13:18 UTC
Labels: bug, help wanted, needs info
