### ISSUE TITLE
Weird git issues making the version -SNAPSHOT

### ISSUE THREAD

**Issue by dwijnand** [sbt/zinc#334] opened 2017-07-05 14:49 UTC
Looks like there are still issues in the build, git uncommitted changes make the version be `-SNAPSHOT` suffixed.

With a little bit of trial and error I found that `git diff-index` and `git -diff-files` are finding some issue with the generated contraband files for inctest; these paths:

```
internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Build.scala
internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/BuildFormats.scala
internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/JsonProtocol.scala
internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Project.scala
internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/ProjectFormats.scala
```

Looks at this crazy shell session, note the timestamps and note that I wasn't doing anything in any other shell at the same time...

```bash
15:22:39 $ echo diff-index && git diff-index HEAD && echo diff-files && git diff-files
diff-index
:100644 100644 7513e854d1fa0beb5d810f58ee307bbc5307eb54 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Build.scala
:100644 100644 5aed8bea2c2b8bb3831beb1ea8d0949190079efe 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/BuildFormats.scala
:100644 100644 c286e76a986af7ffc2f707e5716144c3e5d6bbd4 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/JsonProtocol.scala
:100644 100644 2678426a731a8ab0d19df4f3762c6f15ad3a06e4 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Project.scala
:100644 100644 56375636f4c342f517e6bb3f49638ff16d490724 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/ProjectFormats.scala
diff-files
:100644 100644 7513e854d1fa0beb5d810f58ee307bbc5307eb54 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Build.scala
:100644 100644 5aed8bea2c2b8bb3831beb1ea8d0949190079efe 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/BuildFormats.scala
:100644 100644 c286e76a986af7ffc2f707e5716144c3e5d6bbd4 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/JsonProtocol.scala
:100644 100644 2678426a731a8ab0d19df4f3762c6f15ad3a06e4 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Project.scala
:100644 100644 56375636f4c342f517e6bb3f49638ff16d490724 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/ProjectFormats.scala

15:23:58 $ git diff --cached

15:24:03 $ echo diff-index && git diff-index HEAD && echo diff-files && git diff-files
diff-index
:100644 100644 7513e854d1fa0beb5d810f58ee307bbc5307eb54 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Build.scala
:100644 100644 5aed8bea2c2b8bb3831beb1ea8d0949190079efe 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/BuildFormats.scala
:100644 100644 c286e76a986af7ffc2f707e5716144c3e5d6bbd4 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/JsonProtocol.scala
:100644 100644 2678426a731a8ab0d19df4f3762c6f15ad3a06e4 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Project.scala
:100644 100644 56375636f4c342f517e6bb3f49638ff16d490724 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/ProjectFormats.scala
diff-files
:100644 100644 7513e854d1fa0beb5d810f58ee307bbc5307eb54 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Build.scala
:100644 100644 5aed8bea2c2b8bb3831beb1ea8d0949190079efe 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/BuildFormats.scala
:100644 100644 c286e76a986af7ffc2f707e5716144c3e5d6bbd4 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/JsonProtocol.scala
:100644 100644 2678426a731a8ab0d19df4f3762c6f15ad3a06e4 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/Project.scala
:100644 100644 56375636f4c342f517e6bb3f49638ff16d490724 0000000000000000000000000000000000000000 M	internal/zinc-scripted/src/main/contraband-scala/sbt/internal/inctest/ProjectFormats.scala

15:24:06 $ git st
## 1.0...origin/1.0 [ahead 5]

15:24:07 $ git status
On branch 1.0
Your branch is ahead of 'origin/1.0' by 5 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean

15:24:09 $ echo diff-index && git diff-index HEAD && echo diff-files && git diff-files
diff-index
diff-files

15:24:12 $
```

... 😕❓ something randomly changed in 6 seconds❓

**Comment by dwijnand** [comment] 2017-07-06 14:10
Ok, I just hit this in sbt/lm too..

```shell
$ echo diff-index && git diff-index HEAD && echo diff-files && git diff-files
diff-index
:100644 100644 f63313b93f0a7fcc827a4ab0e1bb1daf002d2202 0000000000000000000000000000000000000000 M	librarymanagement/src/main/contraband-scala/sbt/internal/librarymanagement/ConfigurationReportLite.scala
:100644 100644 b99ec92389256b9c38557d223a7f812c6f26057d 0000000000000000000000000000000000000000 M	librarymanagement/src/main/contraband-scala/sbt/internal/librarymanagement/ExternalIvyConfiguration.scala
:100644 100644 5ddc4a153325519161d773062d9f439b25534d9f 0000000000000000000000000000000000000000 M	librarymanagement/src/main/contraband-scala/sbt/internal/librarymanagement/InlineConfiguration.scala
:100644 100644 0cd006bfafbffa10ee39c0085eeec4c7b45a3768 0000000000000000000000000000000000000000 M	librarymanagement/src/main/contraband-scala/sbt/internal/librarymanagement/InlineIvyConfiguration.scala
...
```

And again `git status` seems to fix it.

I don't even know where I should move this issue to.. Is it a Contraband issue? Is it an sbt-git issue? Is it an sbt issue about source generators?

One thing we should probably try out is bumping the version of sbt-git we're using, in case newer versions of JGit don't have this problem.

**Comment by jvican** [comment] 2017-07-25 16:14
Do you know how to make this actionable Dale?

**Comment by dwijnand** [comment] 2017-07-25 16:26
Requires more research, but it looks like something is causing a caching/race condition in git, which can be force-fixed by invoking `git status`: https://github.com/sbt/zinc/commit/b9cf5c8cc1836c2d61f63edf26d80b7c56bdb983

As I said above, I've no idea where this issue should be opened against.

**Comment by jvican** [comment] 2018-08-27 12:49
Closing, since it cannot be reproduced and we cannot act on it

**Closed as completed by jvican** 2018-08-27 12:49 UTC
Labels: build
