### ISSUE TITLE
Incremental java compilation crashes

### ISSUE THREAD

**Issue by raboof** [sbt/zinc#416] opened 2017-09-27 15:34 UTC
In https://jenkins.akka.io:8498/job/akka-nightly-jdk9/13/console, java compilation crashes:
```
[error] scala.MatchError: null
[error] 	at sbt.internal.inc.ClassToAPI$.reference(ClassToAPI.scala:511)
[error] 	at sbt.internal.inc.ClassToAPI$.parameter(ClassToAPI.scala:375)
[error] 	at sbt.internal.inc.ClassToAPI$.$anonfun$defLike$4(ClassToAPI.scala:353)
[error] 	at sbt.internal.inc.ClassToAPI$.$anonfun$defLike$4$adapted(ClassToAPI.scala:352)
[error] 	at scala.runtime.Tuple3Zipped$.$anonfun$map$1(Tuple3Zipped.scala:48)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
[error] 	at scala.runtime.Tuple3Zipped$.map$extension(Tuple3Zipped.scala:46)
[error] 	at sbt.internal.inc.ClassToAPI$.defLike(ClassToAPI.scala:352)
[error] 	at sbt.internal.inc.ClassToAPI$.methodToDef(ClassToAPI.scala:320)
[error] 	at sbt.internal.inc.ClassToAPI$.$anonfun$structure$1(ClassToAPI.scala:182)
[error] 	at sbt.internal.inc.ClassToAPI$.$anonfun$mergeMap$1(ClassToAPI.scala:398)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error] 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at sbt.internal.inc.ClassToAPI$.merge(ClassToAPI.scala:408)
[error] 	at sbt.internal.inc.ClassToAPI$.mergeMap(ClassToAPI.scala:398)
[error] 	at sbt.internal.inc.ClassToAPI$.structure(ClassToAPI.scala:182)
[error] 	at sbt.internal.inc.ClassToAPI$.x$2$lzycompute$1(ClassToAPI.scala:133)
[error] 	at sbt.internal.inc.ClassToAPI$.x$2$1(ClassToAPI.scala:133)
[error] 	at sbt.internal.inc.ClassToAPI$.instance$lzycompute$1(ClassToAPI.scala:133)
[error] 	at sbt.internal.inc.ClassToAPI$.instance$1(ClassToAPI.scala:133)
[error] 	at sbt.internal.inc.ClassToAPI$.$anonfun$toDefinitions0$1(ClassToAPI.scala:140)
[error] 	at xsbti.api.SafeLazyProxy$$anon$1.get(SafeLazyProxy.scala:26)
[error] 	at xsbti.api.SafeLazy$Impl.get(SafeLazy.java:58)
[error] 	at sbt.internal.inc.ClassToAPI$.$anonfun$process$2(ClassToAPI.scala:29)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:35)
[error] 	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:35)
[error] 	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
[error] 	at sbt.internal.inc.ClassToAPI$.process(ClassToAPI.scala:29)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.readAPI$1(AnalyzingJavaCompiler.scala:143)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$20(AnalyzingJavaCompiler.scala:161)
[error] 	at sbt.internal.inc.classfile.Analyze$.readInheritanceDependencies$1(Analyze.scala:134)
[error] 	at sbt.internal.inc.classfile.Analyze$.$anonfun$apply$16(Analyze.scala:150)
[error] 	at sbt.internal.inc.classfile.Analyze$.$anonfun$apply$16$adapted(Analyze.scala:67)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error] 	at sbt.internal.inc.classfile.Analyze$.apply(Analyze.scala:67)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$19(AnalyzingJavaCompiler.scala:161)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$19$adapted(AnalyzingJavaCompiler.scala:159)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$17(AnalyzingJavaCompiler.scala:159)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:196)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:159)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:104)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:132)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:89)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:115)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:117)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:64)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1403)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1385)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[error] 	at java.base/java.lang.Thread.run(Thread.java:844)
[error] (akka-stream/compile:compileIncremental) scala.MatchError: null
```

This is under sbt 1.0.2 and jdk9.

**Comment by raboof** [comment] 2017-09-27 15:35
This might or might not have to do with the fact that we're adding a `java-jdk9-only` source folder (with jdk9-specific classes) to the build

**Comment by raboof** [comment] 2017-09-27 16:40
Opening the file in a debugger, I see:
* `methodToDef` is called with `public void akka.stream.javadsl.JavaFlowSupport$Flow$1.onNext(java.lang.Object)`
* `defLike` is called with 3 arrays of length 1, containing an empty array of parameter annotations, 'null' and 'false', respectively.

So that's probably:
```
            return new java.util.concurrent.Flow.Processor<In, Out>() {
              @Override public void onError(Throwable t) { sub.onError(t); }
              @Override public void onSubscribe(java.util.concurrent.Flow.Subscription s) { sub.onSubscribe(s); }
              @Override public void onComplete() { sub.onComplete(); }
              @Override public void onNext(In t) { sub.onNext(t); }
              @Override public void subscribe(java.util.concurrent.Flow.Subscriber<? super Out> s) { pub.subscribe(s); }
            };
```

[this commit](https://github.com/akka/akka/pull/23651/commits/0c0b7bf7e5a0ca2f19ef6aeacf36050c2b1e8349) seemed to make thing work locally, though on jenkins it now triggers a different exception...

**Comment by dwijnand** [comment] 2017-09-27 16:41
Fairly sure this is a duplicate of #389.

**Closed as completed by dwijnand** 2017-09-27 16:41 UTC

**Comment by raboof** [comment] 2017-09-27 16:45
Hmm sounds like it indeed - thanks for the reference!
