### ISSUE TITLE
Error reading API from class file

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [sbt/zinc#526] opened 2018-04-05 14:43 UTC
See https://gitter.im/sbt/zinc-contrib?at=5ac413082b9dfdbc3a524751

1. while developing [scalor/zinc/Compiler.scala](https://github.com/random-maven/scalor-maven-plugin/blob/master/src/main/scala/com/carrotgarden/maven/scalor/zinc/Compiler.scala)

and using scalac options `-compileorder:JavaThenScala`

2. consistently getting:
```
[warn] Error reading API from class file : java.lang.ClassNotFoundException
```
for example, in this [travis build](https://travis-ci.org/random-maven/scalor-maven-plugin/jobs/361873230#L1051)

3. but build succeeds regardless of this warning

**Comment by jvican** [comment] 2018-08-27 12:34
This seems to be a problem with the zinc setup you use in Maven? I would be happy to fix this, but we need a reproduction. I'm closing, but if you get to reproduce it please do reopen. Thank you @Andrei-Pozolotin

**Closed as completed by jvican** 2018-08-27 12:34 UTC
Labels: bug
