### ISSUE TITLE
Infinite incremental compilation loop in a Scala 3 project

### ISSUE THREAD

**Issue by ghost** [sbt/zinc#1187] opened 2023-05-15 15:07 UTC
## steps

1. Clone the reproduction project from [here](https://github.com/vasilmkd-jetbrains/sbt-zinc-compilation-bug).
2. Run `sbt` in the cloned project.
3. In the sbt shell, run `clean`, important.
4. In the sbt shell, run `compile` and wait for the compilation to finish, important.
5. Edit any Scala source file in the project. For example, in `src/main/scala/Main.scala`, change the body of the `Main` method to `def Main(args: String*): Unit = println()`.
6. In the sbt shell, run `compile` again.
7. Zinc should enter in an infinite compilation loop.

```
[info] compiling 1 Scala source to /Users/vasil/IdeaProjects/sbt-zinc-compilation-bug/target/scala-3.2.2/classes ...
[info] compiling 2 Scala sources to /Users/vasil/IdeaProjects/sbt-zinc-compilation-bug/target/scala-3.2.2/classes ...
[info] compiling 2 Scala sources to /Users/vasil/IdeaProjects/sbt-zinc-compilation-bug/target/scala-3.2.2/classes ...
[info] compiling 2 Scala sources to /Users/vasil/IdeaProjects/sbt-zinc-compilation-bug/target/scala-3.2.2/classes ...
[info] compiling 2 Scala sources to /Users/vasil/IdeaProjects/sbt-zinc-compilation-bug/target/scala-3.2.2/classes ...
[info] compiling 2 Scala sources to /Users/vasil/IdeaProjects/sbt-zinc-compilation-bug/target/scala-3.2.2/classes ...
[info] compiling 2 Scala sources to /Users/vasil/IdeaProjects/sbt-zinc-compilation-bug/target/scala-3.2.2/classes ...
[info] compiling 2 Scala sources to /Users/vasil/IdeaProjects/sbt-zinc-compilation-bug/target/scala-3.2.2/classes ...
...
```

And the process needs to be killed from the outside.

## problem

Zinc enters an infinite compilation loop and the sbt process needs to be killed forcefully.

## expectation

Compilation should succeed. Furtermore, in the example above, I only edited the `Main.scala` source file, which is not a dependency of `Foo.scala` or `Scope.scala`. My expectation is that only `Main.scala` needs to be recompiled.

**Comment by ghost** [comment] 2023-05-15 15:15
The reproduction project is as minimal as I could get it in a reasonable time.

If I delete `Main.scala` or `empty.scala`, the problem goes away.

I didn't try reducing the code inside `Foo.scala` or `Scope.scala`. I suspect the fact that `trait Foo` and `object Foo` being defined in different files is somehow important.

**Comment by ghost** [comment] 2023-05-15 15:27
I managed to delete all of the code inside `object Scope` and `object Foo` and the issue persists, with the same steps as above.

**Comment by unkarjedy** [comment] 2023-05-16 10:54
Some similar tickets:
[sbt compile goes on indefinitely](https://github.com/sbt/zinc/issues/1120)
[Compiling never stops](https://github.com/sbt/zinc/issues/1101)
and PR 
[Infinite Compile Fix](https://github.com/sbt/zinc/pull/1182) (available in v1.9.0-RC3?)

**Comment by vasilmkd** [comment] 2023-05-31 13:04
I was able to reproduce the problem even when using sbt `1.9.0-RC3`. This issue should be considered actual for all versions of Zinc.

**Comment by Friendseeker** [comment] 2023-12-11 04:21
The infinite compile happens only because two source files generates the same class file.

```
[warn] -- Warning: /Users/jiahuitan/sbt-zinc-compilation-bug/src/main/scala/Foo.scala:1:6 
[warn] 1 |trait Foo {
[warn]   |      ^
[warn]   |      trait Foo and object Foo produce classes that overwrite one another
[warn] one warning found
```

In the example, since `Foo.scala` and `Scope.scala` produce the same class file (because `trait Foo`, `object Foo` clashes), Zinc detects the collision and hence keep invalidating `Foo.scala` and `Scope.scala` for recompilation. 

```
[debug] Invalidated due to generated class file collision: Set(Foo, Foo.Bar, Scope)
```

My opinion is that we flag this issue as won't fix. In fact, perhaps it would be better if Dotty can throw an error instead of warning for class file name collision.

@SethTisue @vasilmkd What is your opinion? If you agree with the above assessment, we can close the issue.

**Comment by lrytz** [comment] 2023-12-11 08:25
@Friendseeker let's check in Scala 3 if there's a reason to not issue an error here. I asked here https://discord.com/channels/632150470000902164/632628489719382036/1183685727117131826, or we can create a dotty ticket later if there's no answer.

**Comment by lrytz** [comment] 2023-12-11 08:26
Ah I see you did that already 🤦‍♂️ I'd say it's a bug that the error is not issued.

**Closed as completed** 2023-12-19 08:07 UTC
