### ISSUE TITLE
v 1.1.3 missing from maven-central

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [sbt/zinc#515] opened 2018-03-25 20:34 UTC
https://github.com/sbt/zinc/releases/tag/v1.1.3

https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/

**Comment by eed3si9n** [comment] 2018-03-25 20:34
Duplicate of https://issues.sonatype.org/browse/MVNCENTRAL-3257

**Comment by Andrei-Pozolotin** [comment] 2018-03-25 20:52
perhaps should post warning on https://github.com/sbt/zinc/releases/tag/v1.1.3

**Comment by dwijnand** [comment] 2018-03-26 09:37
@eed3si9n let us know if there's any news on that issue because it's not publicly visible:

![image](https://user-images.githubusercontent.com/344610/37898772-9d12d11e-30e1-11e8-9285-5d109ac395b9.png)

**Comment by Andrei-Pozolotin** [comment] 2018-03-26 12:46
@eed3si9n can we trust this? :-)
https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.1.3/

**Comment by eed3si9n** [comment] 2018-03-26 12:48
@dwijnand No update on the issue.

@Andrei-Pozolotin Yes! Thanks

**Closed as completed by eed3si9n** 2018-03-26 12:48 UTC

**Comment by Andrei-Pozolotin** [comment] 2018-03-29 19:34
@eed3si9n  please remove
https://github.com/sbt/zinc/releases/tag/v1.1.3
```
Note: 1.1.3 hasn't synced to Maven Central yet.
```

**Comment by dwijnand** [comment] 2018-04-03 13:53
@Andrei-Pozolotin done
